### ISSUE TITLE
Using names in musical types

### ISSUE THREAD

**Issue by rezanayebi** [apollo-lang/apollo#36]
Right now, this throws an error:

```
a : [Pitch] = [A4, C3]
b : Chord = (a, \4)
```

The user should be able to use variable names in derived types.

**Comment by benkogan** [comment]
What kind of error? Parse?

**Comment by rezanayebi** [comment]
Yes, it crashes the REPL, the construct function (in Util) can't deal with names

**Comment by benkogan** [comment]
Just took a quick look. Below is what I think is going to need to happen. In short, key difficulty is that names will have to be left in place until the AST enters the `eval` phase. We may have to make some of the types more general, but we can have the type checker verify that derived types contain only valid values instead of leaving it to Haskell's type system if it comes to it.

---

Currently, [`construct`](https://github.com/apollo-lang/apollo/blob/master/src/Util.hs#L57) tries to break down whatever a chord contains into an array of `Pitch`es. There's no way this can be done before `eval` is reached. One way to fix this might be to change this:

``` haskell
data Chord = Chord [Pitch] Duration
```

into this:

``` haskell
data Chord = Chord [Expr] Duration
```

so that names are left in place. The actions taken by `construct` will be delayed until the values within are needed for making music. As such, `typecheck` will have to take care of verifying these values are type-correct. Further, [when `eval` evaluates a Chord](https://github.com/apollo-lang/apollo/blob/master/src/Eval.hs#L23), it will have to map over what will be the `[Expr]` field of Chord to evaluate all names, etc., within. This could be the point at which the things now done by `construct` could be put into place.

---

Disclaimer: I have the least experience with the musical part of Apollo, so what I just said may be totally off the mark.

**Comment by rezanayebi** [comment]
Yeah I think that's right. For now maybe we can finish whatever is left in the language and come back to that since it involves some refactoring.
